Fix regexps for testing vhost and virtio queues capabilities in kvm
ganeti/ganeti pull request #1569
Opened 2021-01-19 07:28 UTC by regnauld

Updates #1326

Fix typo in _VHOST_RE that made it match kvm --help output in multiple places (on|off would match on OR off and no literal 'on|off')
Harmonize with _VIRTIO_NET_QUEUES_RE (it's -net or -netdev).

With these changes, we match (-net|-netdev) tap from qemu 2.11 all the way to 4.2.1.

Note: \s could just be ' ' here, and the non-capturing (?:..) isn't strictly necessary, but hey.

Thanks to @saschalucas for feedback.

2021-01-23 13:16 UTC, saschalucas requested changes
Thanks for your work and sorry for the delay....

Could you please change the regex to match only the new way with `-netdev`? Down to qemu-2.11 (Bionic), which is the oldest supported qemu version, there is no longer any help message regarding `vhost=` or `fds=` on the deprecated `-net` option. Just following hint:
```
   old way to initialize a host network interface
   (use the -netdev option if possible instead)
```
There is really no need keep old things around. Ganeti uses `-netdev` since 2010 and >=qemu-0.12 (see commit 4b784cf8b4f2deadd3c6074eb3ce6e571b09eee8).

2021-01-25 09:58 UTC, regnauld commented
Ok, pushed update.

2021-01-26 16:05 UTC, saschalucas requested changes
Thanks for switching to `-netdev` only. I don't know the capabilities of the github edit function, but if it is possible for you, then please squash the tow commits into one. If it should not be possible I can do that for you, if you allow the "maintainer edit" option on your PR/branch. ATM it is blocked:

```
$ git push --force regnauld
...
To github.com:regnauld/ganeti.git
 ! [remote rejected]     regnauld-patch-4 -> regnauld-patch-4 (permission denied)

```

2021-01-26 20:52 UTC, regnauld commented
Odd, it's allowed ? Haven't changed 

![image](https://user-images.githubusercontent.com/754461/105903416-228fc700-6020-11eb-90f6-f0d488d6ffb6.png)

... and I don't see anywhere an option to squash & merge :( Either the github UI has changed, or I'm clueless. I can certainly submit a new PR based on a single diff...

2021-01-26 21:06 UTC, iustin commented
@saschalucas - you can "Squash and merge" at merge time, it's no need for the pull request itself to be a single commit.

2021-01-26 21:08 UTC, iustin commented
Ah, I see where the problem is. The repository setting prevents squash&merge, it seems.

![image](https://user-images.githubusercontent.com/550045/105905703-10635800-6023-11eb-9d26-c386ba9b35aa.png)

2021-01-26 21:09 UTC, iustin commented
I've just enabled Squash&Merge, so it should be available now (I see it).

2021-01-26 21:51 UTC, saschalucas approved these changes

2021-01-26 22:13 UTC, saschalucas commented
Thanks @regnauld and @iustin for your help on squashing commits. I've tried to squash and merge from command line (`git merge --squash --ff-only`) with the intent to not have an extra merge commit. Afterwards I changed the commit message and reset author and date to the original (`git commit --amend --author='Phil Regnauld <regnauld@x0.dk>' --date 'Mon Jan 25 10:46:15 2021 +0100'`).

Pushing to master was accepted, but sadly github does not detect this PR to be merged.

2021-01-27 20:51 UTC, saschalucas commented
I'm closing this PR, because it is merged into master (see commit 7e9a1a498defd06bd5037ab04f03ded40d08252e). Next time I'll use the github button for squash and merge, making PRs look better.

2021-01-27 20:51 UTC, closed without merging