try hotplug by default
ganeti/ganeti pull request #1730
Opened 2024-05-21 21:48 UTC by codefritzel

This PR enables hotplug by default for 'gnt-instance modify' and adds the option --no-hotplug to disable hotplug.
A restart should not always be carried out when parameters are changed if this is not necessary.

The parameter --hotplug_if_possible has been removed. Hotplug is now always tried with gnt-instance modify.
A warning is now displayed instead of an error.

See #1548

2024-06-14 21:35 UTC, saschalucas commented on doc/design-hotplug.rst
>  forces live modifications.
... which skips live modifications

2024-06-30 18:20 UTC, rbott commented
This PR also needs to update the QA suite (or it should retain the old parameter), right now it breaks here for KVM Test `TestInstanceModify`):

```
Command: ssh barney.staging.ganeti.org 'gnt-instance modify --net -1:add --hotplug kvm-test-instance02.staging.ganeti.org'
Stderr was:
Usage
=====
  gnt-instance modify <instance-name>

gnt-instance: error: no such option: --hotplug
```

The relevant QA code should be [here](https://github.com/ganeti/ganeti/blob/ceff246e30547d6a10eef27a2d91edce24f05d3e/qa/qa_instance.py#L604-L624)

2024-07-04 17:59 UTC, codefritzel commented
@rbott i have edited the qa code. Can you please run this against the qa again?

2025-01-14 10:59 UTC, rbott commented
Hi @codefritzel,

could you please try to rebase the PR on the current master branch so that we can run the tests and merge the PR?

2025-01-22 22:03 UTC, saschalucas requested changes
Thanks @codefritzel. Can you please also update the man page gnt-instance(8), reflecting the changes regarding the removed option `--hotplug-if-possible` and the reversed logic with `--no-hotplug`?

2025-01-22 22:13 UTC, saschalucas commented on qa/qa_instance.py
>    ]
removing the option `--hotplug` here is good for tests in `_TestKVMHotplug(instance, instance_info)`. However in `TestInstanceModifyDisks(instance)` `--no-hotplug` should be set where disks are added, to represent/test the case without hot plugging.

2025-01-23 20:16 UTC, rbott commented on qa/qa_instance.py
>    ]
There are also `gnt-instance modify` operations for disk/net in `TestInstanceDeviceNames()`, these also need to explicitly disable hotplugging now.

2025-01-26 14:12 UTC, rbott commented
QA Runs started:

- [Bookworm](https://stargazer.ganeti.org/140e8ca6575a1ef572d8a7609316c008eef0255f)
- [Trixie](https://stargazer.ganeti.org/5d9ad6e9676c5fafb6c7603ceb7a2cd42caac218)

2025-01-26 17:35 UTC, saschalucas commented on man/gnt-instance.rst
> -not running or hypervisor is not KVM.
There's a interesting hint in the old manual: `where instances are not running`. For a down instance this looks like this:
```
root@master:~# gnt-instance modify --disk add:size=1g test.vm
Sun Jan 26 14:23:02 2025  - WARNING: Error while executing backend function: [Errno 2] No such file or directory
Sun Jan 26 14:23:02 2025  - INFO: Modification will take place without hotplugging.
...
```
Everything works, but would it be possible to check if the instance is up before trying hotplug?

2025-01-27 15:57 UTC, saschalucas commented on test/py/legacy/cmdlib/instance_unittest.py
> +                         )
syntax issue: dangling `,`

2025-01-28 18:40 UTC, rbott commented
> 
> Thanks @rbott. It seems that Bookworm failed and Trixie is still running? I even can't tell why Bookworm failed... is following the problem?
> 
> ```
> Timeout while talking to the master daemon. Jobs might have been submitted and will continue to run even if the call timed out. Useful commands in this situation are "gnt-job list", "gnt-job cancel" and "gnt-job watch". Error:
> Receive timeout: timed out
> ```

I tried four runs (2 per Debian version each) and three of them failed with the errors you saw. I did not have the time to dig deeper into this, but something seems odd/strange. The fourth run was actually somehow stuck forever during cluster buildup (Ansible was waiting forever for a node to return facts), I had to kill that one manually. I'll start two new runs right now, since there have been more changes.

- [Bookworm](https://stargazer.ganeti.org/61c046fce07d2e21f599d016769c0045cdbbaf97/)
- [Trixie](https://stargazer.ganeti.org/6662516f20da7ba7bc192a82005e633de8d8e0c1/)

Btw, the nightly QA jobs that fail with a runtime of 00:00:00 are mostly due to lack of resources. I did not use auto cleanup for my manual tests runs to leave the option to inspect the instances after a failing QA. That combined with the recently extended runtime of the KVM QA exhaust the server's resources faster than usual.

2025-01-30 12:25 UTC, saschalucas approved these changes
Thanks @codefritzel. LGTM.

2025-01-30 12:30 UTC, saschalucas commented
Seems to hang again:

>     * [Bookworm](https://stargazer.ganeti.org/61c046fce07d2e21f599d016769c0045cdbbaf97/)

```
OSError: [Errno 28] No space left on device
```

>     * [Trixie](https://stargazer.ganeti.org/6662516f20da7ba7bc192a82005e633de8d8e0c1/)
```
Could not shutdown instance 'kvm-test-instance02.staging.ganeti.org': Error while executing backend function: [Errno 11] Resource temporarily unavailable.
```

I have approved this PR now. The changes after last working QA-run are by commit f002bad7712407ad9edef936ad78f10f80d1c8d0, which mostly effects python tests.

2025-01-30 12:31 UTC, merged

2025-01-30 13:31 UTC, rbott commented
For some reason, the QA tests now fail reliably with this PR and only sometimes without it. But I am not sure what might have caused it and if there is any correlation.